name: MuteManager
main: me.cnaude.plugin.MuteManager.MM
version: 0.1.0
description: Tame those mobs!

commands:
    mute:
        description: Mute a player
        usage: /mute [player] [minutes]
        permission: mutemanager.mute        
    unmute:
        description: Unmute a player
        usage: /unmute [player]
        permission: mutemanager.unmute
          
permissions: 
    mutemanager.mute:
        description: Gives player access to /mute.
        default: false 
    mutemanager.unmute:
        description: Gives player access to /unmute.
        default: false 
        