name: MuteManager
main: me.cnaude.plugin.MuteManager.MM
version: 0.9.3
description: Mute those players!
author: Chris Naude
loadbefore: 
  - Essentials
commands:
    mute:
        description: Mute a player
        usage: /mute [player] ([minutes|perm]) ([reason])    
    unmute:
        description: Unmute a player
        usage: /unmute [player]
    mutelist:
        description: List muted players
        usage: /mutelist
permissions: 
    mutemanager.mute:
        description: Gives player access to /mute.
        default: false 
    mutemanager.unmute:
        description: Gives player access to /unmute.
        default: false 
    mutemanager.mutelist:
        description: Gives player access to /mutelist.
        default: false
    mutemanager.listen:
        description: If AdminNotify is true users with this node can read muted messages.
        default: false         